In [3]:
import numpy as np

In [4]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [7]:
#Arreglo de 4 matrices,3 arreglos por matriz ,2 atributos
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [11]:
np.full((2,2),6)

array([[6, 6],
       [6, 6]])

In [10]:
#No inicializas los valores
np.empty([2,2])

array([[1.44635488e-307, 9.34609111e-307],
       [2.89275220e-307, 7.56596412e-307]])

In [12]:
np.array([1,2,3,4,'hola'])

array(['1', '2', '3', '4', 'hola'], dtype='<U11')

In [14]:
np.array([1,2,3,4,3.6])

array([1. , 2. , 3. , 4. , 3.6])

In [16]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [17]:
#matriz
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(5,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [20]:
a = np.array([[5,10,5,25],[1,20,25,20]])

In [22]:
print(a)

[[ 5 10  5 25]
 [ 1 20 25 20]]


In [24]:
b = np.append(a,[1,3])
print(b)

[ 5 10  5 25  1 20 25 20  1  3]


In [41]:
b = np.append(a,[[1,3,2,1]],axis=0)
b

array([[ 5, 10,  5, 25],
       [ 1, 20, 25, 20],
       [ 1,  3,  2,  1]])

In [31]:
c = a.flatten()
print(c)

[ 5 10  5 25  1 20 25 20]


np.delete(a,3)

In [37]:
np.delete(a)

TypeError: _delete_dispatcher() missing 1 required positional argument: 'obj'

In [40]:
np.delete(b,[1],axis=0)

array([[ 5, 10,  5, 25],
       [ 1,  3,  2,  1]])

In [42]:
print(b)

[[ 5 10  5 25]
 [ 1 20 25 20]
 [ 1  3  2  1]]


In [44]:
np.sort(b,axis=0)

array([[ 1,  3,  2,  1],
       [ 1, 10,  5, 20],
       [ 5, 20, 25, 25]])

In [45]:
print(a)

[[ 5 10  5 25]
 [ 1 20 25 20]]


In [50]:
b = a.copy()
print(a)

[[ 2 10  5 25]
 [ 1 20 25 20]]


In [51]:
b[0,0]=2
print(b)

[[ 2 10  5 25]
 [ 1 20 25 20]]


In [52]:
a.ndim

2

In [53]:

a.shape

(2, 4)

In [54]:
a.size

8

In [56]:
a = np.array([1,3,2,5,6,2,3,42,2,2,1,5])

In [57]:
print(a)

[ 1  3  2  5  6  2  3 42  2  2  1  5]


In [59]:
b = a.reshape(3,4)
print(b)

[[ 1  3  2  5]
 [ 6  2  3 42]
 [ 2  2  1  5]]


In [60]:
b[0,0:2]

array([1, 3])

In [61]:
c = b.flatten()
print(c)

[ 1  3  2  5  6  2  3 42  2  2  1  5]


In [62]:
a = np.arange(10,20,2)
b = np.arange(5,10,1)
print(a)
print(b)

[10 12 14 16 18]
[5 6 7 8 9]


In [63]:
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[15 18 21 24 27]
[ 50  72  98 128 162]
[5 6 7 8 9]
[2. 2. 2. 2. 2.]


In [64]:
a = np.arange(10,21,2).reshape(2,-1)
b = np.array([[2],[4],[2]])

In [65]:
print(a)
print(b)

[[10 12 14]
 [16 18 20]]
[[2]
 [4]
 [2]]


In [66]:
#a = 2x3
#b = 3x1
np.dot(a,b)
# 10*2+12*4+14*2
# 16*2+18*4+20*2

array([[ 96],
       [144]])

In [67]:
print(a)

[[10 12 14]
 [16 18 20]]


In [68]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))

15.0
15.0
3.415650255319866


In [70]:
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))

10
20
0
5


In [71]:
np.sqrt(a)

array([[3.16227766, 3.46410162, 3.74165739],
       [4.        , 4.24264069, 4.47213595]])

In [72]:
print(a)

[[10 12 14]
 [16 18 20]]


In [73]:
np.where(a<=12,'Peque','Grande')

array([['Peque', 'Peque', 'Grande'],
       ['Grande', 'Grande', 'Grande']], dtype='<U6')

In [74]:
np.where((a<=18)&(a>=11),'mediano','extremo')

array([['extremo', 'mediano', 'mediano'],
       ['mediano', 'mediano', 'extremo']], dtype='<U7')

In [75]:
print(a)

[[10 12 14]
 [16 18 20]]


In [76]:
a*2

array([[20, 24, 28],
       [32, 36, 40]])

In [77]:
a.transpose()

array([[10, 16],
       [12, 18],
       [14, 20]])

In [80]:
np.where(a<=12,'Peque',\
         np.where(a<=15,'mediano','Si es grande'))

array([['Peque', 'Peque', 'mediano'],
       ['Si es grande', 'Si es grande', 'Si es grande']], dtype='<U12')